StudyCaseAGIT/Models/ErrorViewModel.cs
namespace StudyCaseAGIT.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudyCaseAGIT/Models/ProductionAdjustment.cs
using System.ComponentModel.DataAnnotations;

namespace StudyCaseAGIT.Models
{
    public class ProductionAdjustment
    {
        [Key]
        public int Id { get; set; }
        public int ProductionPlanId { get; set; }
        public int Monday { get; set; }
        public int Tuesday { get; set; }
        public int Wednesday { get; set; }
        public int Thursday { get; set; }
        public int Friday { get; set; }
        public int Saturday { get; set; }
        public int Sunday { get; set; }
        public DateTime AdjustmentDate { get; set; }
    }
}

StudyCaseAGIT/Models/ProductionDetailsViewModel.cs
namespace StudyCaseAGIT.Models
{
    public class ProductionDetailsViewModel
    {
        public ProductionPlan ProductionPlan { get; set; }
        public ProductionAdjustment AdjustPlan { get; set; }
    }
}

StudyCaseAGIT/Models/ProductionPlan.cs
using System.ComponentModel.DataAnnotations;

namespace StudyCaseAGIT.Models
{
    public class ProductionPlan
    {

        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Produksi hari Senin harus diisi.")]
        public int Monday { get; set; }

        [Required(ErrorMessage = "Produksi hari Selasa harus diisi.")]
        public int Tuesday { get; set; }

        [Required(ErrorMessage = "Produksi hari Rabu harus diisi.")]
        public int Wednesday { get; set; }

        [Required(ErrorMessage = "Produksi hari Kamis harus diisi.")]
        public int Thursday { get; set; }

        [Required(ErrorMessage = "Produksi hari Jumat harus diisi.")]
        public int Friday { get; set; }

        [Required(ErrorMessage = "Produksi hari Sabtu harus diisi.")]
        public int Saturday { get; set; }

        [Required(ErrorMessage = "Produksi hari Minggu harus diisi.")]
        public int Sunday { get; set; }

        [Required(ErrorMessage = "Tanggal perencanaan harus diisi.")]
        [DataType(DataType.Date)]
        [CustomValidation(typeof(ProductionPlan), nameof(ValidatePlanDate))]
        public DateTime PlanDate { get; set; }

        public static ValidationResult ValidatePlanDate(DateTime planDate, ValidationContext context)
        {
            DateTime today = DateTime.Today;
            if (planDate.Date < today)
            {
                return new ValidationResult("Tanggal perencanaan tidak boleh di masa lalu.");
            }
            return ValidationResult.Success;
        }
    }
}

StudyCaseAGIT/Controllers/ProductionPlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyCaseAGIT.Context;
using StudyCaseAGIT.Models;
using StudyCaseAGIT.Services;

namespace StudyCaseAGIT.Controllers
{
    public class ProductionPlansController : Controller
    {
        //Task 2
        private readonly ILogger<ProductionPlansController> _logger;
        private readonly ApplicationDbContext _context;

        public ProductionPlansController(ILogger<ProductionPlansController> logger, ApplicationDbContext context)
        {
            _context = context;
            _logger = logger;
        }

        // GET: ProductionPlans
        public async Task<IActionResult> Index()
        {
            return View(await _context.ProductionPlans.ToListAsync());
        }

        // GET: ProductionPlans/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Calculate(int monday, int tuesday, int wednesday, int thursday, int friday, int saturday, int sunday, DateTime plandate, ProductionPlan prodPlan)
        {
            int[] initialPlan = { monday, tuesday, wednesday, thursday, friday, saturday, sunday};
            int[] balancedPlan = ProductionBalancer.BalanceProduction(initialPlan);

            // Simpan data rencana awal ke dalam tabel ProductionPlan
            var productionPlan = new ProductionPlan
            {
                Monday = monday,
                Tuesday = tuesday,
                Wednesday = wednesday,
                Thursday = thursday,
                Friday = friday,
                Saturday = saturday,
                Sunday = sunday,
                PlanDate = plandate
            };

            _context.ProductionPlans.Add(productionPlan);
            _context.SaveChanges();

            // Simpan data hasil adjustment ke dalam tabel ProductionAdjustment
            var productionAdjustment = new ProductionAdjustment
            {
                ProductionPlanId = productionPlan.Id,
                Monday = balancedPlan[0],
                Tuesday = balancedPlan[1],
                Wednesday = balancedPlan[2],
                Thursday = balancedPlan[3],
                Friday = balancedPlan[4],
                Saturday = balancedPlan[5],
                Sunday = balancedPlan[6],
                AdjustmentDate = DateTime.Now
            };
            _context.ProductionAdjustments.Add(productionAdjustment);
            _context.SaveChanges();

            ViewBag.InitialPlan = initialPlan;
            ViewBag.BalancedPlan = balancedPlan;

            return RedirectToAction(nameof(Index));

        }


        // GET: ProductionPlans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productionPlan = await _context.ProductionPlans
                .FirstOrDefaultAsync(m => m.Id == id);
            var adjustPlan = await _context.ProductionAdjustments
                .FirstOrDefaultAsync(n => n.ProductionPlanId == id);

            if (productionPlan == null && adjustPlan == null)
            {
                return NotFound();
            }

            ViewBag.ProductionPlan = productionPlan;
            ViewBag.AdjustPlan = adjustPlan;

            return View();
        }
    }
}

StudyCaseAGIT/Views/ProductionPlans/Create.cshtml
@model StudyCaseAGIT.Models.ProductionPlan

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ProductionPlan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Calculate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Monday" class="control-label"></label>
                <input asp-for="Monday" class="form-control" />
                <span asp-validation-for="Monday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tuesday" class="control-label"></label>
                <input asp-for="Tuesday" class="form-control" />
                <span asp-validation-for="Tuesday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wednesday" class="control-label"></label>
                <input asp-for="Wednesday" class="form-control" />
                <span asp-validation-for="Wednesday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thursday" class="control-label"></label>
                <input asp-for="Thursday" class="form-control" />
                <span asp-validation-for="Thursday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Friday" class="control-label"></label>
                <input asp-for="Friday" class="form-control" />
                <span asp-validation-for="Friday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Saturday" class="control-label"></label>
                <input asp-for="Saturday" class="form-control" />
                <span asp-validation-for="Saturday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sunday" class="control-label"></label>
                <input asp-for="Sunday" class="form-control" />
                <span asp-validation-for="Sunday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlanDate" class="control-label"></label>
                <input asp-for="PlanDate" class="form-control" />
                <span asp-validation-for="PlanDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudyCaseAGIT/Views/ProductionPlans/Details.cshtml
@{
    ViewData["Title"] = "Production Plan Details";

    // Getting data from ViewBag
    var productionPlan = ViewBag.ProductionPlan as StudyCaseAGIT.Models.ProductionPlan;
    var adjustPlan = ViewBag.AdjustPlan as StudyCaseAGIT.Models.ProductionAdjustment;
}

<h1>Production Plan Details</h1>

<div>
    <h4>Production Plan Comparison</h4>
    <hr />
    <table class="table table-bordered">
        <thead>
            <tr>
                <th></th>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
                <th>Saturday</th>
                <th>Sunday</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Original Plan</td>
                <td>@(productionPlan != null ? productionPlan.Monday.ToString() : "N/A")</td>
                <td>@(productionPlan != null ? productionPlan.Tuesday.ToString() : "N/A")</td>
                <td>@(productionPlan != null ? productionPlan.Wednesday.ToString() : "N/A")</td>
                <td>@(productionPlan != null ? productionPlan.Thursday.ToString() : "N/A")</td>
                <td>@(productionPlan != null ? productionPlan.Friday.ToString() : "N/A")</td>
                <td>@(productionPlan != null ? productionPlan.Saturday.ToString() : "N/A")</td>
                <td>@(productionPlan != null ? productionPlan.Sunday.ToString() : "N/A")</td>
            </tr>
            <tr>
                <td>Adjusted Plan</td>
                <td>@(adjustPlan != null ? adjustPlan.Monday.ToString() : "N/A")</td>
                <td>@(adjustPlan != null ? adjustPlan.Tuesday.ToString() : "N/A")</td>
                <td>@(adjustPlan != null ? adjustPlan.Wednesday.ToString() : "N/A")</td>
                <td>@(adjustPlan != null ? adjustPlan.Thursday.ToString() : "N/A")</td>
                <td>@(adjustPlan != null ? adjustPlan.Friday.ToString() : "N/A")</td>
                <td>@(adjustPlan != null ? adjustPlan.Saturday.ToString() : "N/A")</td>
                <td>@(adjustPlan != null ? adjustPlan.Sunday.ToString() : "N/A")</td>
            </tr>
        </tbody>
    </table>
</div>

<div>
    <h4>Details</h4>
    <hr />
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td>Plan Date</td>
                <td>@(productionPlan != null ? productionPlan.PlanDate.ToString("d") : "N/A")</td>
            </tr>
            <tr>
                <td>Adjustment Date</td>
                <td>@(adjustPlan != null ? adjustPlan.AdjustmentDate.ToString("d") : "N/A")</td>
            </tr>
        </tbody>
    </table>
</div>

<div>
  @*    <a asp-action="Edit" asp-route-id="@productionPlan?.Id" class="btn btn-warning">Edit</a> *@
    <a asp-action="Index" class="btn btn-primary">Back to List</a>
</div>

StudyCaseAGIT/Views/ProductionPlans/Index.cshtml
@model IEnumerable<StudyCaseAGIT.Models.ProductionPlan>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>No</th>
            <th>@Html.DisplayNameFor(model => model.First().Monday)</th>
            <th>@Html.DisplayNameFor(model => model.First().Tuesday)</th>
            <th>@Html.DisplayNameFor(model => model.First().Wednesday)</th>
            <th>@Html.DisplayNameFor(model => model.First().Thursday)</th>
            <th>@Html.DisplayNameFor(model => model.First().Friday)</th>
            <th>@Html.DisplayNameFor(model => model.First().Saturday)</th>
            <th>@Html.DisplayNameFor(model => model.First().Sunday)</th>
            <th>@Html.DisplayNameFor(model => model.First().PlanDate)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>@Html.DisplayFor(modelItem => item.Monday)</td>
                <td>@Html.DisplayFor(modelItem => item.Tuesday)</td>
                <td>@Html.DisplayFor(modelItem => item.Wednesday)</td>
                <td>@Html.DisplayFor(modelItem => item.Thursday)</td>
                <td>@Html.DisplayFor(modelItem => item.Friday)</td>
                <td>@Html.DisplayFor(modelItem => item.Saturday)</td>
                <td>@Html.DisplayFor(modelItem => item.Sunday)</td>
                <td>@Html.DisplayFor(modelItem => item.PlanDate)</td>
                <td>
                    @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
                    <a asp-action="Details" class="btn btn-primary" asp-route-id="@item.Id">Details</a>
                    @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
                </td>
            </tr>
            i++;
        }
    </tbody>
</table>

StudyCaseAGIT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudyCaseAGIT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudyCaseAGIT.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="ProductionPlans" asp-action="Index">StudyCaseAGIT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductionPlans" asp-action="Index">Production Plan</a>
                        </li>
@*                          <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                         </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - StudyCaseAGIT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>